#!/usr/bin/env bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Installs the helm-unittest plugin, pinned by version and checksum, from the
# upstream release archive (upstream's documented offline-install layout: the
# tgz carries plugin.yaml plus the untt binary). Deliberately NOT installed via
# `helm plugin install <git-url>`: that fetches whatever the mutable version tag
# points to at install time and executes the plugin's install hook, which
# downloads and runs an unverified release binary — including on the release
# manager's workstation via release-rc.sh.
#
# Unlike install-yq.sh/install-oras.sh (CI-only, single Linux platform), this
# script also runs on the release manager's workstation (macOS or Linux, amd64
# or arm64) via release-rc.sh, so it resolves the host platform and verifies the
# downloaded archive against the per-platform SHA-256 pinned in
# hack/tool-checksums.txt (regenerated by `make sync-tool-checksums`). Renovate
# bumps HELM_UNITTEST_VERSION; the sync regenerates the digests. Idempotent:
# skips the install when the pinned version is already present.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# renovate: datasource=github-releases depName=helm-unittest/helm-unittest
HELM_UNITTEST_VERSION="${HELM_UNITTEST_VERSION:-v1.1.2}"

want="${HELM_UNITTEST_VERSION#v}"
installed="$(helm plugin list 2>/dev/null | awk '$1 == "unittest" { print $2 }')"
if [ "${installed}" = "${want}" ]; then
  echo "helm-unittest ${HELM_UNITTEST_VERSION} already installed"
  exit 0
fi

# Map the host OS/arch to the helm-unittest offline-install archive token
# (helm-unittest-<os>-<arch>-<version>.tgz).
os="$(uname -s)"
arch="$(uname -m)"
case "${os}" in
  Linux) plat_os="linux" ;;
  Darwin) plat_os="macos" ;;
  *) echo "unsupported OS '${os}' for helm-unittest" >&2; exit 1 ;;
esac
case "${arch}" in
  x86_64 | amd64) plat_arch="amd64" ;;
  arm64 | aarch64) plat_arch="arm64" ;;
  *) echo "unsupported architecture '${arch}' for helm-unittest" >&2; exit 1 ;;
esac
platform="${HELM_UNITTEST_PLATFORM:-${plat_os}-${plat_arch}}"

asset="helm-unittest-${platform}-${want}.tgz"
url="https://github.com/helm-unittest/helm-unittest/releases/download/${HELM_UNITTEST_VERSION}/${asset}"
tmpdir="$(mktemp -d)"
trap 'rm -rf "${tmpdir}"' EXIT

curl -fsSL "${url}" -o "${tmpdir}/${asset}"
"${REPO_ROOT}/scripts/verify-tool-checksum.sh" "${tmpdir}/${asset}" "${HELM_UNITTEST_VERSION}/${asset}"

# A stale/partial plugin dir breaks reinstall; remove it first (best effort,
# then remove the directory itself in case the uninstall metadata is broken).
helm plugin uninstall unittest >/dev/null 2>&1 || true
plugins_dir="$(helm env HELM_PLUGINS)"
dest="${plugins_dir}/helm-unittest"
rm -rf "${dest}"
mkdir -p "${dest}"
tar -xzf "${tmpdir}/${asset}" -C "${dest}"

echo "helm-unittest ${HELM_UNITTEST_VERSION} installed from checksum-verified archive"
